{
 "title": "Kubernetes DNS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "content": "<center><h1>Kubernetes 1.11.4</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 0 },
   "content": "<center><h1>Kubernetes 1.9.0</h1></center>"
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dns_success_total" }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dns_error_total" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dns_success_total / (dns_success_total + dns_error_total)"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dns_error_total / (dns_success_total + dns_error_total)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dns_success_total" }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dns_error_total" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dns_success_total / (dns_success_total + dns_error_total)"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dns_error_total / (dns_success_total + dns_error_total)"
    }
   ]
  },
  {
   "title": "DNS Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dns_success_total / (dns_success_total + dns_error_total)",
     "legendFormat": "DNS success lookup"
    },
    {
     "expr": "dns_error_total / (dns_success_total + dns_error_total)",
     "legendFormat": "DNS error lookup"
    }
   ]
  },
  {
   "title": "DNS Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dns_success_total / (dns_success_total + dns_error_total)",
     "legendFormat": "DNS success lookup"
    },
    {
     "expr": "dns_error_total / (dns_success_total + dns_error_total)",
     "legendFormat": "DNS error lookup"
    }
   ]
  }
 ]
}